inherits = "catppuccin_mocha"

"ui.background" = { fg = "white" }
"ui.statusline" = { fg = "white" }

"diagnostic.info" = { modifiers = ["dim"] }
"diagnostic.hint" = { modifiers = ["dim"] }
"diagnostic.debug" = { modifiers = ["dim"] }
"diagnostic.warning" = { modifiers = ["dim"] }
"diagnostic.error" = { modifiers = ["dim"] }
