theme = "rose_pine_clean"

[editor]
scrolloff = 0
color-modes = true
line-number = "relative"
true-color = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[keys.normal]
X = "extend_line_above"

[editor.statusline]
left = ["mode", "spinner", "file-base-name"]

[editor.lsp]
display-messages = false
auto-signature-help = false
