theme = "kanagawa"

[editor]
color-modes = true
true-color = true

[editor.gutters]
layout = ["diagnostics", "spacer", "diff"]


[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[keys.normal]
X = "extend_line_above"

[editor.statusline]
left = ["mode", "spinner", "file-base-name"]

[editor.lsp]
display-messages = false
auto-signature-help = false
goto-reference-include-declaration = false
