theme = "catppuccin_trans"

[editor]
scrolloff = 0
color-modes = true
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
X = "extend_line_above"

[editor.statusline]
left = ["mode", "spinner", "file-base-name"]
