theme = "everforest_light"

[editor]
scrolloff = 0
color-modes = true
line-number = "relative"
true-color = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

# [editor.whitespace.render]
# space = "all"
# tab = "all"

[keys.normal]
X = "extend_line_above"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-base-name"]

[editor.lsp]
display-messages = false
auto-signature-help = false
goto-reference-include-declaration = false
